browser
fs/qa-test-task-android pull request #6
Opened 2021-07-12 13:47 UTC by GalievBulat

2021-07-12 13:55 UTC, nailshaykhraziev requested changes

2021-07-12 13:55 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/feature/browser/BrowserFragment.kt
> +class BrowserFragment : Fragment(R.layout.fragment_news_browser) {
пустая строка после начала класса

2021-07-12 13:55 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/feature/browser/BrowserFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
пустая строка перед методом

2021-07-12 13:55 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/feature/news/NewsFragment.kt
> +                    .actionNewsFragmentToBrowserFragment(it.url).let { directions ->
перенос строки не нужен, имя для скоуп переменной можно не давать.

2021-07-12 13:55 UTC, nailshaykhraziev commented on app/src/main/res/navigation/btm_nav.xml
> +        android:label="BrowserFragment" >
В стрингах параметр добавить

2021-07-12 13:58 UTC, SergeyOzerov commented on app/build.gradle
> +    implementation 'androidx.preference:preference-ktx:1.1.1'
тут дублирование зависимостей, удалить

2021-07-13 08:41 UTC, nailshaykhraziev approved these changes

2021-07-13 08:45 UTC, merged