Feature/sections screen
fs/qa-test-task-android pull request #7
Opened 2021-07-14 16:19 UTC by Birugov

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/data/guardiannews/model/Category.kt
> +    var isChecked: Boolean
плохая практика делать поля var без необходимости

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/feature/viewmodel/CategoryFragmentViewModel.kt
> +                it[position] = item
состояние, как я и говорил, надо изменять тут. 
```suggestion
                it[position] = item.copy(isChecked = !item.isChecked)
```

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/res/layout/fragment_category.xml
> +        android:layout_height="match_parent"
0dp

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/res/layout/sections_recycler_elem.xml
> +        android:layout_width="403dp"
что-то странная длинна TextView. wrap content и настрой margin.

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +            }
вот это перенести в метод bind у holder'a. И лучше безопасно кастить через as?. Мало ли у вас в верстке другой класс станет и тогда начнет крашится.

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +            }
во-первых, листенеры в onBind навешивать плохая практика. Во-вторых, если сделаешь изменения во viewModel, о которых я написал ниже, то в этом не будет необходимости.

2021-07-15 09:09 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    inner class SectionsViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView),
у вас же ViewBinding подключен. Лучше его передавать в конструктор. Можешь посмотреть как сделано в другом адаптере. Тогда не придется вызывать findViewById.

2021-07-15 09:23 UTC, nailshaykhraziev requested changes

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
> +
extra line

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
> +    private val categoriesVM: CategoryFragmentViewModel by viewModel()
rename categoriesVM to viewModel

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
> +            val data = it
val data = it
don't need here

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
> +        binding.sectionsRv.apply {
rvSections

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
>  }
add empty line after class

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/CategoryFragment.kt
> +            layoutManager = LinearLayoutManager(context)
лучше в хмл задать манаджер

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +
extra line

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    ListAdapter<Category, RecyclerView.ViewHolder>(
переносы строки не нужны:
listAdapter<Category, RecyclerView.ViewHolder>(DIFF_CALLBACK) { перенос строки

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder {
ViewHolder = SectionsViewHolder(

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    ListAdapter<Category, RecyclerView.ViewHolder>(
Поменяй RecyclerView.ViewHolder на SectionsViewHolder, тогда не придется всякими кастами в onBindViewHolder заниматься

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +
extra line

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    interface OnItemClickListener {
Я б лучше лямбду передавал вместо интерфейса, ну ладно. Пусть будет так

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +
extra lines

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/data/guardiannews/model/CategoryResponseBase.kt
> +)
добавить пустую строку после класса

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/feature/viewmodel/CategoryFragmentViewModel.kt
> +
extra line

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/feature/viewmodel/CategoryFragmentViewModel.kt
> +class CategoryFragmentViewModel(private val retrofit: GuardianRetrofit):ViewModel() {
add spaces between :

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/res/layout/fragment_category.xml
> +        />
перенос строки не нужен

2021-07-15 09:23 UTC, nailshaykhraziev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="cv_sections_elem_margin">5dp</dimen>
отступы обычно числа кратные 4, поэтому тут у тебя будет или 4 или 8

2021-07-15 12:55 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    private lateinit var elem: Category
а это тебе тут зачем? убрать

2021-07-15 12:59 UTC, SergeyOzerov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +            itemView.let {
зачем тут let? и попросил использовать сейвовый каст.
` (itemView as? MaterialCardView)?.run {
                    isChecked = elem.isChecked
                }`

2021-07-15 13:27 UTC, nailshaykhraziev commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    private lateinit var elem: Category
Насчет этого не уверен

2021-07-15 13:27 UTC, Birugov commented on app/src/main/java/com/flatstack/qatesttask/adapters/SectionsRecyclerAdapter.kt
> +    private lateinit var elem: Category
я же убрал

2021-07-15 13:32 UTC, SergeyOzerov submitted a review, later dismissed

2021-07-16 09:52 UTC, nailshaykhraziev approved these changes

2021-07-16 09:53 UTC, merged